export const CFG = {
  viewport: { width: 1440, height: 900 },
  timeout: 90000,
  scrollStep: 200,
  scrollDelay: 100,
  concurrency: 8,
  retries: 2,
  dlTimeout: 15000,
  stripDomains: [
    'events.framer.com',
    'sentry.io',
    'api.framer.com',
    'stats.g.doubleclick.net',
    'google-analytics.com',
  ],
  stripSelectors: [
    'script[src*="events.framer.com"]',
    '#__framer-badge-container',
    '#__framer-badge',
    '.w-webflow-badge',
    '#WIX_ADS',
    '.wix-ads',
    '#wix-badge',
    'link[href*="editorbar"]',
    'link[href*="canvas-sandbox"]',
    'script[src*="framer.com/bootstrap"]',
  ],
};
